# Cloudflare Pages 构建配置

# 构建命令和输出目录
[build]
  command = "yarn build"
  output_directory = "out"
  node_version = "18"

# 环境变量
[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "4.9.2"
  NODE_OPTIONS = "--max-old-space-size=4096"

# 构建缓存配置
[build.cache]
  includes = [
    "node_modules/**",
    ".yarn/cache/**",
    ".next/cache/**"
  ]